# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-19 14:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_articoloconfermanto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nuovo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nuovi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.Articolo')),
            ],
        ),
        migrations.RemoveField(
            model_name='articoloconfermanto',
            name='articoli_confermati',
        ),
        migrations.DeleteModel(
            name='Articoloconfermanto',
        ),
    ]
