# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-19 14:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_auto_20170919_1411'),
    ]

    operations = [
        migrations.AddField(
            model_name='articolo',
            name='convalida',
            field=models.BooleanField(default=False),
        ),
    ]
