# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-19 14:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_articolo_convalida'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nuovo',
            name='nuovi',
        ),
        migrations.DeleteModel(
            name='Nuovo',
        ),
    ]
