# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-26 17:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_auto_20170919_1438'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articolo',
            options={'ordering': ['-published_date']},
        ),
        migrations.AddField(
            model_name='articolo',
            name='foto',
            field=models.ImageField(default='', upload_to='photos', verbose_name='Foto allegata'),
        ),
    ]
